account/urls.py
from django.contrib import admin
from django.urls import path
from .views import registerView, user_login, user_logout
from django.conf.urls.static import static
from django.conf import settings

app_name = "accounts"

urlpatterns = [
    path('login/', user_login, name="login_url"),
    path('register/',registerView, name="register_url"),
    path('signout/', user_logout, name = "signout"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookaspeakers/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('speakerapp.urls')),
    path('search/', include('searchapp.urls')),
    path('profile/', include('speaker_profile.urls')),
    path('register/', include('registerPembicara.urls')),
    path('account/', include('account.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

 

speaker_profile/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'speaker_profile'


urlpatterns = [
    path('<id>', views.profile, name='profile'),
    path('<id>/check_availability/', views.check_availability, name='check_availability'),
]

speaker_profile/models.py
from django.db import models
from registerPembicara.models import Pembicara

# Create your models here.
class Booking(models.Model):
    CITIES = [
        ('Jakarta', 'Jakarta'),
        ('Bandung', 'Bandung'),
        ('Bogor', 'Bogor'),
        ('Depok', 'Depok'),
    ]
    
    name = models.CharField(max_length=30)
    event_name = models.CharField(max_length=30)
    event_date = models.DateField()
    topic = models.CharField(max_length=20)
    city = models.CharField(max_length=7, choices=CITIES)
    phone_number = models.IntegerField()
    email = models.EmailField()
    speaker = models.ForeignKey(Pembicara, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

speaker_profile/forms.py
from django import forms
from .models import Booking
from django.forms import TextInput

class CreateBooking(forms.ModelForm):
    class Meta:
        model = Booking
        fields = ('name', 'event_name', 'event_date', 'topic', 'city', 'phone_number', 'email')
    def __init__(self, *args, **kwargs):
        super(CreateBooking, self).__init__(*args, **kwargs)
        self.fields['event_date'].widget = TextInput(attrs={
            'type': 'date',
            'class': 'dateinput',
        })
        self.fields['topic'].widget = TextInput(attrs={
            'data-url': "{% url speaker_profile:check_availability %}",
            'onkeyup': 'checkavailability(this)'
        })

speaker_profile/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from .forms import CreateBooking
from .models import Booking
from registerPembicara.models import Pembicara
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import F
from django.contrib.auth.decorators import login_required

# Create your views here.
def profile(request, id):
    form = CreateBooking(request.POST or None)
    speaker = Pembicara.objects.get(id = id)
    if (request.method == 'POST' and form.is_valid()):
        map = {
            'name': request.POST['name'],
            'event_name': request.POST['event_name'],
            'event_date': request.POST['event_date'],
            'topic': request.POST['topic'],
            'city': request.POST['city'],
            'phone_number': request.POST['phone_number'],
            'email': request.POST['email'],
            'form': CreateBooking(),
            'data': speaker,
        }
        new_entry = Booking(name=map['name'], event_name=map['event_name'], event_date=map['event_date'], topic=map['topic'], city=map['city'], phone_number=map['phone_number'], email=map['email'], speaker=speaker)
        new_entry.save()
        speaker.counter = F('counter') + 1
        speaker.save()
        return render(request, 'profile.html', map)
    else:
        map = {
            'form': CreateBooking(),
            'data': speaker,
        }
        return render(request, 'profile.html', map)

def check_availability(request, id):
    if request.method == "GET":
        response_data = {}
        event_date = request.GET.get('event_date', False)
        check = None
        try:
            try:
                speaker = Pembicara.objects.get(id = id)
                filtered = Booking.objects.filter(speaker = speaker)
                check = filtered.get(event_date = event_date)
            except ObjectDoesNotExist as e:
                pass
            except Exception as e:
                raise e
            if not check:
                response_data['available'] = 'ok'
            else:
                response_data['available'] = 'no'
        except Exception as e:
            response_data['available'] = 'no'
        return JsonResponse(response_data)

speaker_profile/templates/profile.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style_profile.css' %}">
{% endblock css %}
{% block content %}
    {% if request.user.is_authenticated %}
    <div class="page row">
        <div class="profile col">
            <div class="insideprofile">
                {% if data.photo %}
                <img src={{data.photo.url}} alt="fotospeaker" class="photo">
                {% endif %}
                <h3 class="name"> {{data.first_name}} {{data.last_name}} </h3>
                <p class="title">{{data.position}}</p>
                <p class="category">{{data.category}}</p>
                <p class="desc">{{data.desc}}</p>
                <p class="left"> <span><img src="{% static 'images/location.png' %}" alt=""></span>          {{data.city}}</p>
                <p class="left"> <span><img src="{% static 'images/badge.png' %}" alt=""></span>          Rp {{data.fee}}</p>
                <button class="contactbutton" onclick="window.location.href='mailto:{{data.email}}'">Contact {{ data.first_name }}</button>
            </div>
        </div>
        <form method="POST" class="bookingform col">
            {% csrf_token %}
            {{form}}
            <span id='status' style="font-weight: 300; margin: 1.5%"></span><br>
            <button class="formbutton" type="submit">Book</button>
        </form>
    </div>
    {% else %}
    <p class="prompt">please login first</p>
    <p>{{ user.username }}</p>
    {% endif %}
{% endblock %}
{% block js %}
    <script type='text/javascript' src="{%  static 'js/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/addons.js' %}"></script>
    <script type='text/javascript'>
        var previous_topic = '';
        var in_ajax = 0;
        function checkTopic() {
            changed = $("#id_event_date").val();
            if ((previous_topic != changed) && (changed != '')){
                in_ajax = 1;
                $("#status").html("<img src='{% static 'images/ajax-loader.gif' %}' />");
                jQuery.get("{% url 'speaker_profile:check_availability' id=data.id %}", {event_date: $("#id_event_date").val()},
                    function(response){
                        if(response.available == "ok"){
                            $("#status").html("Yay, this speaker is available!");
                            $("#status").css('color', '#619658')
                        } else {
                            $("#status").html("Sorry, this speaker is not available on the chosen date:( Please choose another date or try other speakers.");
                            $("#status").css('color', '#B53E3E')
                        }
                    });
            }
            previous_topic = changed;
        }
        $(function() {
            setInterval("checkTopic()", 1000);
        });
</script>
{% endblock js %}