account/urls.py
from django.contrib import admin
from django.urls import path
from .views import registerView, user_login, user_logout
from django.conf.urls.static import static
from django.conf import settings

app_name = "accounts"

urlpatterns = [
    path('login/', user_login, name="login_url"),
    path('register/',registerView, name="register_url"),
    path('signout/', user_logout, name = "signout"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookaspeakers/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('speakerapp.urls')),
    path('search/', include('searchapp.urls')),
    path('profile/', include('speaker_profile.urls')),
    path('register/', include('registerPembicara.urls')),
    path('account/', include('account.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

 

speakerapp/urls.py
from django.contrib import admin
from django.urls import path
from .views import index, getCounter
from django.conf.urls.static import static
from django.conf import settings

app_name = "homepage"

urlpatterns = [
    path('', index, name="home"),
    path('getCounter/', getCounter, name="getCounter")
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models

# Create your models here.

account/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.template import RequestContext
from django.contrib.auth import authenticate, login, logout
from django.http.response import HttpResponse

# Create your views here.

response = {}


def registerView(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('accounts:login_url')
    else:
        form = UserCreationForm()

    return render(request, 'registeracc.html', {'form' : form })

def user_login(request):
    response['username'] = "username"
    if request.method == "POST":
         username = request.POST['username']
         password = request.POST['password']
         user = authenticate(request, username=username, password=password)
         if user is not None:
            login(request, user)
            request.session['username'] = username
            response['username'] = request.session['username']
            return redirect('homepage:home')
         else:
            resp = {}
            resp['pesan'] = "Password and username not match"
            return render(request, 'login.html',resp)
    else:
        return render(request, 'login.html',response)



def user_logout(request):
    request.session.flush()
    logout(request)
    return redirect('homepage:home')

account/templates/login.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'login.css' %}">
{% endblock css %}
    {% block content %}
    <div class="body">
<head>
    <title>Login</title>
</head>
<body>
    <header>
            
    </header>
    {% if user.is_authenticated %}
    <div class="login">
        <h1>Logout</h1>
                <a href="{% url 'accounts:signout' %}" id="logout"> <button class="btn">Sign Out</button></a>
      
        <a class="btn" href="{% url 'homepage:home' %}">Home</a>
        
    </div>
    {% else %}
    <div class="login">
        <h1>LOGIN</h1>
        
            <form method="POST">
                    {% csrf_token %}
                
                    <div class="textbox">
                        <input type="username" name="username" id="username" class="input" placeholder="Username">
                    </div>
                    <div class="textbox">
                        <input type="password" name="password" id="password" class="input" placeholder="Password">
                    </div>
                <button class="btn" id="login">Sign In</button>
                <a class="btn" href="{% url 'accounts:register_url' %}">Sign Up</a>
            </form>

        <a class="btn" href="{% url 'homepage:home' %}">Home</a>
        <h1 style="font-size:130%;">{{ pesan }}</h1>
        
    </div>
    {% endif %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"> </script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>
</div>
{% endblock %}

account/templates/logout.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

{% block css %}<link rel="stylesheet" href="{% static 'login.css' %}">{% endblock css %}
    {% block content %}
    <div class="body">
<head>
    <title>Login</title>
</head>
<body>
    <header>
            
    </header>
    <div class="login-box">
        <h1>Logout</h1>
                <a href="{% url 'accounts:signout' %}" id="logout"> <button class="btn">Sign Out</button></a>
      
        <a class="btn" href="{% url 'homepage:home' %}">Home</a>
        
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"> </script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>
</div>
{% endblock %}

account/templates/registeracc.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

{% block css %}<link rel="stylesheet" href="{% static 'login.css' %}">{% endblock css %}
    {% block content %}
    <div class="body">
<div class="container">
<head>

        <title>Register</title>
</head>
<body>
        <div >
                <div class="register">
                    <h1>Create New Account</h1>
                            <form method="POST">
                                    {% csrf_token %}
                                {{form.as_p}}
                                <button class="btn">Register</button>
                                <a class="btn" href="{% url 'accounts:login_url' %}">Sign In</a>
                            </form>
                </div>
            </div>
    
</body>
</div>
</div>
{% endblock %}