account/urls.py
from django.contrib import admin
from django.urls import path
from .views import registerView, user_login, user_logout
from django.conf.urls.static import static
from django.conf import settings

app_name = "accounts"

urlpatterns = [
    path('login/', user_login, name="login_url"),
    path('register/',registerView, name="register_url"),
    path('signout/', user_logout, name = "signout"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookaspeakers/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('speakerapp.urls')),
    path('search/', include('searchapp.urls')),
    path('profile/', include('speaker_profile.urls')),
    path('register/', include('registerPembicara.urls')),
    path('account/', include('account.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

 

registerPembicara/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = "register"

urlpatterns = [
    path('', views.register, name="form"),
    path('confirm', views.confirm, name="confirm"),
    path('getData', views.getData)
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

searchapp/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name="search"

urlpatterns = [
    path('', views.search, name="search"),
    path('getData/', views.getData, name="get-data"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

speaker_profile/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'speaker_profile'


urlpatterns = [
    path('<id>', views.profile, name='profile'),
    path('<id>/check_availability/', views.check_availability, name='check_availability'),
]

speakerapp/urls.py
from django.contrib import admin
from django.urls import path
from .views import index, getCounter
from django.conf.urls.static import static
from django.conf import settings

app_name = "homepage"

urlpatterns = [
    path('', index, name="home"),
    path('getCounter/', getCounter, name="getCounter")
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

speakerapp/models.py
from django.db import models

# Create your models here.

speakerapp/views.py
from django.shortcuts import render
from django.core import serializers
from django.http import HttpResponse
from django.middleware.csrf import get_token
from registerPembicara import forms, models

def index(request):
    form = forms.RegisterForm()
    pembicaras = models.Pembicara.objects.all().order_by('-counter')[0:3]
    pemb = {
        'pembicara_data' : pembicaras,
    }
    return render(request, "index.html", pemb)

def getCounter(request):
    pembicaras = models.Pembicara.objects.all().order_by('-counter')[0:3]
    pembicara_list = serializers.serialize('json', pembicaras)
    return HttpResponse(pembicara_list, content_type="text/json-comment-filtered")

speakerapp/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block css %}<link rel="stylesheet" href="{% static 'style.css' %}">{% endblock css %}
    {% block content %}
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>

        <a href="#home" target="_self">
            <div class="button_up position-fixed">
                <i class="fas fa-angle-double-up"></i>
            </div>
        </a>
        <div id= "home" class="texthome container-fluid">
          <div class="txtcol col container">
            <div class="texthome2 row">
              BookaSpeaker
            </div>
            <div class="texthome3 row">
                is a platform to connect speakers and clients around Indonesia.
            </div>
            {% if user.is_authenticated %}
            <div class="texthome3 row" style="padding-top: 9%; font-weight: bold;">
                Welcome {{user.username}}!
            </div>
            <div class="texthome3 row">
                Lets us know you’re a good speaker
            </div>
            {% else %}
            <div class="texthome3 row" style="padding-top: 9%;">
                Lets us know you’re a good speaker
            </div>
            {% endif %}
            
            <a class="btnhome btn btn-primary" href="{% url 'register:form' %}" role="button">Join as Speaker</a>

          </div>
        </div>
        <div class="text2 container-fluid">
          <div class="topspeak container-fluid">
            Top Speakers 
          </div>
          <div class="row" style="padding: 5%; margin-right: 0;" id="change">
                {% csrf_token %}
           {% for pembicara in pembicara_data %}
            <div class="col " id="jquery">
                <div class="topspeak2 container">
                        {% if pembicara.photo %}
                        <img src={{pembicara.photo.url}} class="img-fluid imgtop" alt="Responsive image">
                        {% endif %}
                    <div class="container-fluid speaknama">
                        {{ pembicara.first_name }} </br> {{ pembicara.last_name }} 
                    </div>
                    <div class="container-fluid speaknama speakjabatan">
                            {{ pembicara.position }}
                    </div>
          
                    <div class="container-fluid " style="width: 100%;">
                        <div class="container speaknama speakkategori">
                                {{ pembicara.category }}
                        </div>
                    </div>
                    <div class="container-fluid speaknama speakket">
                        <i class="fas fa-map-marker-alt"></i>  {{ pembicara.city }} </br>
                        <i class="fas fa-tags"></i> Rp {{ pembicara.fee }}
                    </div>
                    <div class="container-fluid speaknama">
                        <a href="{% url 'speaker_profile:profile' id=pembicara.id %}">See More</a>
                    </div>
                    <div class="container-fluid speaknama counter">
                        Been booked by {{ pembicara.counter }} people
                    </div>
                    
                    
                </div>
            </div>
            {% endfor %}
          </div>
          <div class="row" style="margin-right: 0;">
              <a class="btnspeak btn btn-primary" href="{% url 'search:search' %}" role="button">More Speakers</a>
          </div>
        </div>
        <script>
            $(document).ready(function(){
              $(document).mousemove(function(event){
                $.ajax({
                    method: 'GET',
                    url: 'getCounter',
                    success: function(response){
                        console.log(response);
                        $("#change").empty();
                        for(let i=0; i<response.length; i++){
                            var id = response[i].pk;
                            console.log(id);
                            $("#change").append(
                                '<div class="col" id="jquery">' +
                                '<div class="topspeak2 container">'+
                            
                                '<img src="/media/'+response[i].fields.photo+'" class="img-fluid imgtop" alt="Responsive image">'+
                                '<div class="container-fluid speaknama">'+
                                response[i].fields.first_name + '</br>' + response[i].fields.last_name + '</div>'+
                                '<div class="container-fluid speaknama speakjabatan">' +
                                response[i].fields.position + '</div>' + 
                                '<div class="container-fluid " style="width: 100%;">'+
                                '<div class="container speaknama speakkategori">' +
                                response[i].fields.category + '</div>' + '</div>' +
                                '<div class="container-fluid speaknama speakket">' +
                                    '<i class="fas fa-map-marker-alt"></i>'+  response[i].fields.city + '</br>' +
                                    '<i class="fas fa-tags"></i> Rp'+ response[i].fields.fee +
                                '</div>' +
                                '<div class="container-fluid speaknama">' +
                                '<a href="'+ 'profile/'+id+'">See More</a>'+
                                '</div>' + 
                                '<div class="container-fluid speaknama counter"> Been ordered by '+
                                response[i].fields.counter +  ' people' + 
                                '</div>' +
                                '</div>' + '</div>'
                        );
                    }
                        
                    }
                })
              });
            });
            $( "#change" ).mouseenter(function() {
                $(".topspeak2").css('transform', 'scale(1.2)');
            })
            $( ".topspeak2" ).mouseleave(function() {
                    
            });
        </script>
        <div class="txtcopy container-fluid">
            Copyright © 2019 BookaSpeaker
        </div>
    {% endblock %}