account/urls.py
from django.contrib import admin
from django.urls import path
from .views import registerView, user_login, user_logout
from django.conf.urls.static import static
from django.conf import settings

app_name = "accounts"

urlpatterns = [
    path('login/', user_login, name="login_url"),
    path('register/',registerView, name="register_url"),
    path('signout/', user_logout, name = "signout"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookaspeakers/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('speakerapp.urls')),
    path('search/', include('searchapp.urls')),
    path('profile/', include('speaker_profile.urls')),
    path('register/', include('registerPembicara.urls')),
    path('account/', include('account.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

 

registerPembicara/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = "register"

urlpatterns = [
    path('', views.register, name="form"),
    path('confirm', views.confirm, name="confirm"),
    path('getData', views.getData)
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

searchapp/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name="search"

urlpatterns = [
    path('', views.search, name="search"),
    path('getData/', views.getData, name="get-data"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

speakerapp/urls.py
from django.contrib import admin
from django.urls import path
from .views import index, getCounter
from django.conf.urls.static import static
from django.conf import settings

app_name = "homepage"

urlpatterns = [
    path('', index, name="home"),
    path('getCounter/', getCounter, name="getCounter")
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700|Raleway:400,700&display=swap" rel="stylesheet"> 
        <!-- <link rel="stylesheet" href="font-awesome/css/font-awesome.min.css" /> -->
        <link rel="stylesheet" href="{% static 'base.css' %}">
        <title>BookaSpeaker</title>
        <script src="https://code.jquery.com/jquery-3.4.1.js"crossorigin="anonymous"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jquerymobile/1.4.5/jquery.mobile.min.css">
        <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
        {% block css %}{% endblock css %}
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        {% block js %}{% endblock js %}
        </head>
        <body>
            <nav id = "navbar" class="navbar navbar-expand-lg navbar-light position-sticky fixed-top">
                <a class= "logo" href="{% url 'homepage:home'%}">
                    <img src="{% static 'logo.png' %}">
                </a>
            <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item ml auto">
                        <a class="nav-link" href="{% url 'homepage:home'%}">Home</a>
                    </li>
                    <li class="nav-item ml auto">
                        <a class="nav-link" href="{% url 'search:search' %}">Speakers</a>
                    </li>
                    <li class="nav-item ml auto">
                        <a class="nav-link" href="{% url 'register:form' %}">Register</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item ml auto">
                        <a class="nav-link" href="{% url 'accounts:login_url' %}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item ml auto">
                        <a class="nav-link" href="{% url 'accounts:login_url' %}">Login</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>  
        {% block content %}
        {% endblock %}
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquerymobile/1.4.5/jquery.mobile.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
        <script src="https://kit.fontawesome.com/4b60c8a34d.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        </body>
    </html>